kind: ConfigMap
apiVersion: v1
metadata:
  name: isvd-proxy-config
  namespace: dev-ibm-ciam
data:
  server.pem: |
   -----BEGIN PRIVATE KEY-----
    MIIJQwIBADANBgkqhkiG9w0BAQEFAASCCS0wggkpAgEAAoICAQDqXDtTVpqcbAhK
    IVe5EAk19++pH3AF0z8O87UC51lR5rIttH44afHV4RoDBs4HFi35W6z/fj/CFJQC
    fRX8OUj6b/XSKmH/2V739JJeUar7JREsd7uvJENPocF00IntOHtdRKdKLCV25A0b
    ua7IwsGv4RS8HTVYZR43rhE++UGPWW8Axvpw6Q6ohncwsyJ1ClLN5Pc20W01uRxW
    xeJWfknp0VLrv+Z1lAXVCxCihUOCwVERzfcnR4x3ahmR8pnOD83R/hkKy4PQEr/O
    rVfe7pzyukRSDi08hxt3efeZo7g4IINtQzP1cR4mSuSpckVPiuhBqkL75CVYUl/5
    nH61d+yGJ0foKISyDWlXgmiWhVwWg1M7Ky5jH2Jb5fCUCsD0yhnPfPs7+Lbfz1Lp
    kIggX0sh3tjYGcnpxUIiZAgN/S921zd1OAAby/jn0icVvXHx+YlO3I96nqTDRU/8
    uCVDtanBUwefkFLTuh3EKa/gznm2zffscq/zl/ArT2KozjM/AfLOQr56x2wNp/Mg
    efIXHkaOmGkgZJm7/ab98z6CeuWWykJsJuojUUbOSGmxa8djJA6JDi04qInfjKjp
    6NeXmVbGi8s6PE7pHWBUwgEQQVAz13Xjh53/uNn7haPS6uh7BuYExZqFlDzWWGCT
    wai3x4rhdtxGkYSqL8gd2hEJ4DGI+QIDAQABAoICAE3olFY7i5Flfon6NJnSYWV+
    Az9zMn/VPni/fpS1COXnraLxBibF3X2u48FO0U3cyzLCjauvsg1YXu3G3HipKIAM
    mSkhKsvtXJtMRB4zwwXTSDbCpPNvuCqwSMoHC1r/dE9Io95N97Ri0pK9cwPNbqsD
    xatVgGbe0qFK7fPD084OOo8FFrtTVqqibNwVKObEpEtLCv2/uDDsVSXpibkcKYEf
    s5OoiznaF+g/UevdJljA4CztjfSSXflSnaZ9gjDU4ySkdnm2tx6EJRxVVslHBIjS
    cCThDpu5BGH++1cpbHPIJzi65vp4fL/ZFNPZp33uXRB7Q+JN8TY/yCUIJ7023TsG
    wKq8c/Ok7tz36aR1F05xq/GOTQ4fiaXz9md8xDHDF8sup8yIa2em1cjs2szNyJCu
    FSxiIPP1uY6IPcsRe6mDGcAIuEpXJRktLASwKej7MCnCAvB2K4OyZX6YlD81rFh7
    +XrhHNpPSIiGR+wxxuVFGQd4aKXguegyvX1nzBgEOzGgaLZOsWnE6y5BM9qSVBqQ
    KVRG4DCplH4wVFTWtbmuAX7eHKxyYGXKO7L2jbzQPaxuPC13od1ZlcC3b2X0OQWJ
    tkpeIuXlB97SDukOtAigSXz+PObyL7MyGqGKNHkVAlKNPn+IFbsD8hIyWXrOhJ9V
    Y3w9V93PnZv+hb7zmaiDAoIBAQDs2ceh1PsNMEi+6kP1aSfi/gs2VJLY7UFCU1yD
    HYwO2MEG236Bj/0C+L2pPhARBZDukhrQDAIBv1qgR4s9xKmZJ2Oh7BRa+tA8sSLB
    fjKbk8mn/ReUrFbHXnXOLkqW2wtMJalhJpswrsS3PkzcfyV/gBB7DrNDw84sXHux
    vXZW0YKthND2TEVEUozmY0PrVzdwsqaGxYIPCRwbOY27KOdAyx1agkdehSkqOPnk
    eGnCGR8tVEqHktoZ7ag38FsMNJp1scdFKGvboCOGSHnKDtUcNAefLguf2A5yCPbH
    KRX2yrh5Z3dF1rqMQBLhwAvYxENeWZH4glD7ytI/GQJDzrqvAoIBAQD9TugI4Omg
    +V2ljVjPjn7GSDBP3LqDLKa222mPnt4DwN/ClAIPyk9B6OmJHPU7WurExC5gTfPP
    yLExy+esrC/WQDVfV1EnAcQnIMux0Vc12m+xt5PCu+GmfGevtsh/hjoUd28tUD4a
    3TyHHPyymhooVyy6fz+GfzR6jPUZezt70IrVhnqg39rtabk837wpAPeiDyawXftL
    HrFYnY50li5SLyrw3F6ZrzNm5WB/C6zhx5RDWAOj3caYjIWQoqUX2OHGKdoI7nOH
    QdGM92juhVMYRaUthmaFoeE2AxoT8XW4JPBDC5hFxV+tZg7nEZQq5cgG4xkr3Ueu
    9tHPmhjtSUDXAoIBAC2XMgUloPmF7MrK/y/TAPmBmxjnKKkW6jPhJfKbEmWdNXKj
    d3NrCvGyfZeBOch9AMvbVcvsM8qwUbp+awAFxfuUCGqXrcdhdgnost758rXdubhb
    UFmu3rlbpmN8p6DoIwGSUktACilRys3W8SaUVtx3AzUcvEbz/tCtMKYi6Q+HHpdV
    9H8kaUTgevyx6NX5INPRn5pblFBemYloB68aDYF8V3cfkqtQCH93HirrPrg867Jn
    Aj2cd9z70SCLZIsx6PV0tf3K7RAGgDAN7VuGhWD7ZuguDdDD3uv2a8IkV3T8youb
    7eqEjb4Ha1sHA4DDLpCPvzhNpVcCUHwSzUvOFEMCggEBAKS9Mo7Dp223f73xZTbn
    V2+g9zqZNPumiG4X2Fk9WupZ/6xOEeEvE8irr2Yq3RpTEKgTZo3fZJdX0FWwZOWZ
    viq663ssEG0r6uP/ojntCajOfSG5YHGfOyvJcK2IVHELXK5+1mFD9IAILhs5MOb+
    7dAakc5gf3H7PKgPEEAYMyFdCU3A/fOuYnVQ8tWyNG7+YA6Xh/Pfy1SZi4E0Rrdw
    DIQKhQTMbQHKPcXHm7BEaZUU9Umu7f8edtAzY5IjFPejZ4I3KcPxQFVQ6vWg2i91
    qgr5EGnBJN/33b4A2m7p9ENkUpVn7wpBSO4+l6aTeidD9Yj1HSO376zMfLtlXpzD
    rVUCggEBAIwk5ycsLZFGSH/jdSyJ6tvfPBIIHYOSSTxhKQoZ6+0rwujklviL/JZF
    E5WlVK+arPRHRgbwVEl+f/l+U2ecV2GQ7gqHdfOihyqFxYsWs6moqpqimaXfMJ7d
    habm7y5Rm9p6+tjFhTHiL+vwcQ2kVfw+oMQn0+T8sf150eIGk3YTr2o1+oBXgSRL
    SlwwomxE8JOQ0hpZRm2OEjnskzk0NBJj43mmHfenlJ0Ctkt1sPClGHQOnEZjsYVr
    yXnHKAg7KDu4dVCcIj3C7fWLRnTSPA1mUvhZmgpZktCJriRvaznAK1lccjBDUPEv
    /9pGIETfyaf6c9AzPazTIU6rqk3HhQc=
    -----END PRIVATE KEY-----
    -----BEGIN CERTIFICATE-----
    MIIFjTCCA3WgAwIBAgIUL4nhZmCBPOvUPJp03X4dj/ZKPxMwDQYJKoZIhvcNAQEL
    BQAwVjELMAkGA1UEBhMCSU4xFTATBgNVBAcMDERlZmF1bHQgQ2l0eTEcMBoGA1UE
    CgwTRGVmYXVsdCBDb21wYW55IEx0ZDESMBAGA1UEAwwJc2Rzc2VydmVyMB4XDTI0
    MDcyNjEyMDYyMloXDTI1MDcyNjEyMDYyMlowVjELMAkGA1UEBhMCSU4xFTATBgNV
    BAcMDERlZmF1bHQgQ2l0eTEcMBoGA1UECgwTRGVmYXVsdCBDb21wYW55IEx0ZDES
    MBAGA1UEAwwJc2Rzc2VydmVyMIICIjANBgkqhkiG9w0BAQEFAAOCAg8AMIICCgKC
    AgEA6lw7U1aanGwISiFXuRAJNffvqR9wBdM/DvO1AudZUeayLbR+OGnx1eEaAwbO
    BxYt+Vus/34/whSUAn0V/DlI+m/10iph/9le9/SSXlGq+yURLHe7ryRDT6HBdNCJ
    7Th7XUSnSiwlduQNG7muyMLBr+EUvB01WGUeN64RPvlBj1lvAMb6cOkOqIZ3MLMi
    dQpSzeT3NtFtNbkcVsXiVn5J6dFS67/mdZQF1QsQooVDgsFREc33J0eMd2oZkfKZ
    zg/N0f4ZCsuD0BK/zq1X3u6c8rpEUg4tPIcbd3n3maO4OCCDbUMz9XEeJkrkqXJF
    T4roQapC++QlWFJf+Zx+tXfshidH6CiEsg1pV4JoloVcFoNTOysuYx9iW+XwlArA
    9MoZz3z7O/i2389S6ZCIIF9LId7Y2BnJ6cVCImQIDf0vdtc3dTgAG8v459InFb1x
    8fmJTtyPep6kw0VP/LglQ7WpwVMHn5BS07odxCmv4M55ts337HKv85fwK09iqM4z
    PwHyzkK+esdsDafzIHnyFx5GjphpIGSZu/2m/fM+gnrllspCbCbqI1FGzkhpsWvH
    YyQOiQ4tOKiJ34yo6ejXl5lWxovLOjxO6R1gVMIBEEFQM9d144ed/7jZ+4Wj0uro
    ewbmBMWahZQ81lhgk8Got8eK4XbcRpGEqi/IHdoRCeAxiPkCAwEAAaNTMFEwHQYD
    VR0OBBYEFLtJL4F7sNQbO012Crr9OH3VR8NwMB8GA1UdIwQYMBaAFLtJL4F7sNQb
    O012Crr9OH3VR8NwMA8GA1UdEwEB/wQFMAMBAf8wDQYJKoZIhvcNAQELBQADggIB
    AKdk5iTCtheRntKEpnxxUv5dATq9/szr/U/dJ+ffadZkkauRwo8HAdA1aSmYSmDt
    OCW+1L6MUco4kOlVS03LRRlcWm+muwFFXPCV3isksUaZv4DySQ55kS9x/0Jb3jtJ
    UBa9Q6OynLCeOt+nOIEkzOkWIms20YPCkK93jhaLQnX4AsRMGtSNJRvY1JkIo2SP
    cAdrCahFPXthBkfZS84abuFN4pdINZcVVXPfXrbYqhulH4du9/kHsSPB1dkT6RgD
    GwEhB5+noiPZqu0F0l43xY7IljFEiXj0aXESHXryFPQ3qjrIFLsecAVrcQ8zhwQU
    0+CS6GgCYYfayYQnwWAZKnImG8hdHRjUF9c2Gdp+IRbwiS8UpGPIoNjcAahTV5ai
    L7qFZ98qrEPaat8MNSMIJ9ZxTcuXMs5NHnxldJWbLqEm5iIgA0XZdKrhqATnV18R
    VKl+GHwTnbWh5lZYrxGwB8ShGPD3k/NocCfxtK48OzKcbF+oTj+cwelXV9nTGbXr
    dkjTNsPQY5TKkWqyYWxg+axNCB/1AdXAq6sgb/D1nAvotaWtbj2uo1Z9SJ3fJoQg
    fGg4peNNf4JN1vP9tlGNFYsaepBoisrxc+AEmrBtBB46qEYsENVtgYeDqTswmczH
    ua7FlGMudXAdv1Bfr9DpdOe4QV3183SyxT4Wy+JEb4wl
    -----END CERTIFICATE-----
  config.yaml: |
    debug:
      startup: true
    general:
      admin:
        pwd: passw0rd1
      id: test-proxy-server1
      key-stash: "B64:EAAAAE9jV05DUGVVUTcvZXFTcHYqe1JSN1M3VWlTdk+lUB3EMXtq3uL1K7svhZ82pVAdxDF7at7i9Su7L4WfNrtSmOe+PYzspVAdxDF7at7i9Su7L4WfNrtSmOe+PYzsae8zaQ+Iq9Q="
      license:
        accept: standard
        key: "R2VuZXJpYzotMToxOjCCAacGCSqGSIb3DQEHAqCCAZgwggGUAgEBMQ8wDQYJYIZIAWUDBAIBBQAwGwYJKoZIhvcNAQcBoA4EDEdlbmVyaWM6LTE6MaAAMYIBXTCCAVkCAQEwSDA8MQswCQYDVQQGEwJ1czEMMAoGA1UEChMDaWJtMQ0wCwYDVQQLEwRpc3ZhMRAwDgYDVQQDEwdzaWduaW5nAgh4PC0gxTSNfzANBglghkgBZQMEAgEFAKBpMBgGCSqGSIb3DQEJAzELBgkqhkiG9w0BBwEwHAYJKoZIhvcNAQkFMQ8XDTIyMTAxMDA2NTgyN1owLwYJKoZIhvcNAQkEMSIEICNI9qWOUQ1SXQXNbnOMT5HDinpaosSdz13WyWX2XFLiMA0GCSqGSIb3DQEBAQUABIGARibpp/5rnoMDqO9rOSKFwx3m0bbYGgvkiJtDbHcRHTzErgvxqpYV0NLa9CpsCrzySCxiC2v5Xh4XhkalH6IABYWv+ZWRkh1aen8lshEYR1EAgs8llh3FmQ9xRGTJp1XkacRx3XI/s5dNNtWGEqoc1eX3cCXIG9WvO7Uoxc84b+I="
      ports:
        ldap: 9389
        ldaps: 9636
      ssl:
        cert-label: 'server-key'
      audit:
        enabled: true
        log-to-file: true
        operation:
          search: true
      json-logging: false
    proxy:
      server-groups:
      - name: serverGroup1
        servers:
        - bind-method: Simple
          id: pvcomsds
          name: pvcomsds
          target: ldaps://isvd-server:9636
          user:
            dn: cn=root
            password: passw0rd1
      suffixes:
      - base: o=sample
        name: sample
        num-partitions: 1
        servers:
        - index: 1
          name: pvcomsds
          role: primarywrite
      - base: dc=pvb,dc=vn
        name: pvb
        num-partitions: 1
        servers:
        - index: 1
          name: pvcomsds
          role: primarywrite
      - base: secAuthority=Default
        name: secAuthority
        num-partitions: 1
        servers:
        - index: 1
          name: pvcomsds
          role: primarywrite
    keyfile:
      keys:
      - label: 'server-key'
        key: "@/var/isvd/config/server.pem"
---
kind: Deployment
apiVersion: apps/v1
metadata:
  name: isvd-proxy-server1
  namespace: dev-ibm-ciam
  labels:
    app: isvd-proxy-server1

spec:
  replicas: 1
  selector:
    matchLabels:
      app: isvd-proxy-server1

  template:
    metadata:
      labels:
        app: isvd-proxy-server1

    spec:
      restartPolicy: Always
      serviceAccountName: isvd
      serviceAccount: isvd

      containers:
        - name: isvd-proxy-server1
          
          readinessProbe:
            exec:
              command:
                - /sbin/health_check.sh
            initialDelaySeconds: 5
            timeoutSeconds: 1
            periodSeconds: 10
            successThreshold: 1
            failureThreshold: 3

          livenessProbe:
            exec:
              command:
                - /sbin/health_check.sh
                - livenessProbe
            initialDelaySeconds: 5
            timeoutSeconds: 1
            periodSeconds: 10
            successThreshold: 1
            failureThreshold: 3

          env:
            - name: YAML_CONFIG_FILE
              value: /var/isvd/config/config.yaml

          ports:
            - containerPort: 9636
            
          imagePullPolicy: Always
          volumeMounts:
            - name: config-volume
              mountPath: /var/isvd/config
          image: 'icr.io/isvd/verify-directory-proxy:latest'

      volumes:
        - name: config-volume
          configMap:
            name: isvd-proxy-config
